unit:
  replicaCount: 3
  image:
    repository: lyra-unit
    tag: dev
    pullPolicy: IfNotPresent
  server:
    bindAddress: "0.0.0.0:7070"
  ioMode: basic
  storage:
    size: 2Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1"

log:
  level: info
