[server]
bind_address = "127.0.0.1:7070"

[wal]
dir = "/tmp/lyra-wal"

[storage]
dir = "/tmp/lyra-storage"

[log]
level = "info"

[catalog]
service_address = "localhost:6648"
namespace = "default"

[query]
bind_address = "127.0.0.1:50051"
endpoint = "http://127.0.0.1:50051"
