apiVersion: v1
kind: ConfigMap
metadata:
  name: lyra-config
  labels:
    app.kubernetes.io/name: lyra
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  unit.toml: |
    io_mode = "{{ .Values.unit.ioMode }}"

    [server]
    bind_address = "{{ .Values.unit.server.bindAddress }}"

    [wal]
    dir = "/data/wal"

    [storage]
    dir = "/data/storage"

    [segments]
    dir = "/data/segments"

    [log]
    level = "{{ .Values.log.level }}"

  xunit.toml: |
    [catalog]
    backend = "{{ .Values.catalog.backend }}"
    service_address = "{{ .Values.catalog.serviceAddress }}"
    namespace = "{{ .Values.catalog.namespace }}"

    [log]
    level = "{{ .Values.log.level }}"

  functions.toml: |
    [catalog]
    backend = "{{ .Values.catalog.backend }}"
    service_address = "{{ .Values.catalog.serviceAddress }}"
    namespace = "{{ .Values.catalog.namespace }}"

    [log]
    level = "{{ .Values.log.level }}"

  orchestrator.toml: |
    [catalog]
    backend = "{{ .Values.catalog.backend }}"
    service_address = "{{ .Values.catalog.serviceAddress }}"
    namespace = "{{ .Values.catalog.namespace }}"

    [orchestrator]
    bind_address = "{{ .Values.orchestrator.server.bindAddress }}"
    endpoint = "{{ .Values.orchestrator.server.endpoint }}"

    [log]
    level = "{{ .Values.log.level }}"
