apiVersion: v1
kind: Service
metadata:
  name: lyra-unit
  labels:
    app.kubernetes.io/name: lyra-unit
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: lyra-unit
  ports:
    - port: 7070
      targetPort: 7070
      name: grpc
    - port: 7071
      targetPort: 7071
      name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: lyra-unit-headless
  labels:
    app.kubernetes.io/name: lyra-unit
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: lyra-unit
  ports:
    - port: 7070
      targetPort: 7070
      name: grpc
{{- if .Values.orchestrator.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: lyra-orchestrator
  labels:
    app.kubernetes.io/name: lyra-orchestrator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: lyra-orchestrator
  ports:
    - port: 50051
      targetPort: 50051
      name: flight-sql
{{- end }}
